title: 13 to 33
description: Tutorials for the ages
author: "Nay San"

theme: minima

base_url: /13to33
repository: fauxneticien/13to33

# Minima social links
github_username: fauxneticien
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
