version: '3'

services:
  jekyll:
    build:
      context: .
    # command: jekyll serve --watch --force_polling --incremental --port 8080 -H 0.0.0.0 --livereload --livereload-port 35729 --baseurl /13to33
    command: jekyll serve --watch --force_polling --port 8080 -H 0.0.0.0 --livereload --livereload-port 35729 --baseurl /13to33
    volumes:
      - .:/srv/jekyll
    ports:
      - '8080:8080'
      - '35729:35729'
    environment: 
      RUBYOPT: '-W0'
      JEKYLL_ENV: production 

